# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
# 
#     steps:
#       - uses: actions/checkout@v2
#         with:
#          token: ${{secrets.PAT}}
#       - name: Use Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: '16.x'
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - run: git config --global user.email "garu_sridhar@yahoo.com"
#       - run: git config --global user.name "half-blood-prince"
#       - run: git status
      
#       - run: npm install
#       - run: npm run build
#       - run: git status
#       - name: 'Upload Artifact'
#         uses: actions/upload-artifact@v2
#         with:
#           name: build
#           path: build/
#           retention-days: 1
      
      
  deploy:
    name: Deploy
#     needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.PAT}}
      - run: git branch -a
      - run: git fetch --all
      - run: git branch -a
      - run: git checkout gh-pages
      - run: git push origin gh-pages 
#       - name: Download a single artifact
#         uses: actions/download-artifact@v2
#         with:
#           name: build
      - run: git status
      
      
